---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: app
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          env:
          - name: POSTGRES_HOST
            value: "postgres-service-new"
          - name: POSTGRES_PORT
            value: "5432"
          envFrom:
            - secretRef:
                  name: secrets
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-new
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: postgres