---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          envFrom:
            - secretRef:
                  name: secrets
          volumeMounts:
          - name: {{ .Values.postgres.volumes.name }}
            mountPath: {{ .Values.postgres.volumes.mountPath }}
      volumes:
      - name: {{ .Values.postgres.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.volumes.persistentVolumeClaim.claimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.volumes.persistentVolumeClaim.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: 
  - {{ .Values.postgres.volumes.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres.volumes.persistentVolumeClaim.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-new
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
