apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: app
        image: nl7robbins/recipe-practice-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secrets
