apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: app
        image: nl7robbins/recipe-practice-app:latest
        ports:
        - containerPort: 3000
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: DB_PASSWORD
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: APP_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: config
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: DB_PORT
