apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: app
        image: nl7robbins/recipe-practice-app:latest
        ports:
        - containerPort: 3000
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "2000m"
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: POSTGRES_PASSWORD
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: APP_PORT
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: config
                key: POSTGRES_DB
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: DB_PORT
