app:
  port: 3000
  replicaCount: 3
  autoscaling:
    enabled: false
  image:
    repository: "nl7robbins/recipe-practice-app"
    tag: "latest"
  imagePullSecrets:
    name: regcred
  resources:
    requests:
      memory: "64Mi"
      cpu: "500m"
    limits:
      memory: "500Mi"
      cpu: "2000m"
postgres:
  host: "host.docker.internal"
  port: "5432"