app:
  port: 3000
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    repository: "nl7robbins/recipe-practice-app"
    tag: "latest"
  imagePullSecrets:
    name: regcred
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "500Mi"
      cpu: "2000m"
postgres:
  host: "postgres-service-new"
  port: 6543
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "500Mi"
      cpu: "2000m"
  volumes:
    mountPath: /var/lib/postgresql/data
    name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-pvc-new
      accessModes: ReadWriteOnce
      storage: 1Gi